### ISSUE TITLE
Some rules do not run in WikiCheck but run in Recent Changes...

### ISSUE THREAD

**Issue by milekpl** [languagetool-org/languagetool-community-website#14]
For example, PRZE:

http://community.languagetool.org/rule/show/PRZE?lang=pl&subId=1&textToCheck=...a+i+utworzenia+niekt%C3%B3rych+gromad+%28w+brzmieniu+zatwierdzonym+prze+Rad%C4%99+Ministr%C3%B3w+uchwa%C5%82%C4%85+nr+368%2F68+z+dnia+17.XII.1968+r.+z+mo...

But see here:

http://community.languagetool.org/feedMatches/list?lang=pl&notFixedFilter=1440&categoryFilter=&filter=PRZE

What's the problem? Maybe there's a version mismatch between Recent Changes check and the WikiCheck? Anyway, it's quite counterintuitive.

**Comment by danielnaber** [comment]
Closing as WikiCheck is not maintained anymore.
