### ISSUE TITLE
Usability: make correction field larger for larger mistakes

### ISSUE THREAD

**Issue by milekpl** [languagetool-org/languagetool-community-website#2]
For Polish, there is an important mistake -- missing comma between two component sentences in a compound sentence -- which is difficult to fix using WikiCheck because the correction box is tiny. Make the correction box proportional to the length of the error.

See for example:

http://community.languagetool.org/wikiCheck/pageCheck?url=http%3A%2F%2Fpl.wikipedia.org%2Fwiki%2FKsi%25C4%2599%25C5%25BCniczka_%28singel%29&lang=pl

**Comment by danielnaber** [comment]
Closing as WikiCheck is not maintained anymore.
