### ISSUE TITLE
error in rule creator with a correct example

### ISSUE THREAD

**Issue by jaumeortola** [languagetool-org/languagetool-community-website#23]
An error occurs when a correct example is added in the rule creator (expert mode):

```
<rule id="CONFUSION_OF_BED_BAD" name="confusion of bed/bad">
    <pattern>
        <token>bed</token>
        <token>English</token>
    </pattern>
    <message>Did you mean <suggestion>bad English</suggestion>?</message>
    <example correction="bad English">Sorry for my <marker>bed English</marker>.</example>
    <example>Sorry for my bad English</example>
</rule>
```
Error: 
`
Sorry, an error occurred trying to check your rule: No signature of method: org.languagetool.RuleEditorController.cleanMarkers() is applicable for argument types: (org.languagetool.rules.CorrectExample) values: [Sorry for my bad English]`

**Comment by danielnaber** [comment]
Thanks, this is fixed now.
