### ISSUE TITLE
Integration of various dictionaries

### ISSUE THREAD

**Issue by Pav-Ved** [languagetool-org/languagetool-community-website#25]
Hello there, I have been looking into the language tool for sometime to help us (a small team of freelancing copyeditors) with certain basic editing tasks, we would like to be a part of this online community to further enhance the system for various editing tasks with out inputs and experience of copyediting

For starters I had some questions and a clarity on these issues would be of great help.

1. One thing that I would like to know is which  dictionaries are integrated into the system for spellcheck. As we could not find that information in the grammar.xml?
2. Are the dictionaries separate for US English and UK English?
3. Is there a possibility to integrate scientific dictionaries such as Index Medicus?

**Comment by danielnaber** [comment]
Thanks for your interest in LT - could you please post your questions to http://forum.languagetool.org, that's a better place for questions and discussions.
