### ISSUE TITLE
Prevent users from misusing the email field when suggesting words for the dictionary

### ISSUE THREAD

**Issue by janschreiber** [languagetool-org/languagetool-community-website#26]
On https://community.languagetool.org/suggestion/edit, we're receiving a lot of suggestions that look like this:
![2017-02-03-222748_1024x768_scrot](https://cloud.githubusercontent.com/assets/4381288/22609481/a2981bd4-ea61-11e6-9b2d-1a8e47611066.png)
In other words, some users are apparently unaware that they are supposed to enter an email address.
Instead they end up sending us a misspelled word plus a bona fide correction (which can be annoying if it happens too often, because it costs us time).

**Suggestion:**

- Add a basic sanity check to the email text field. Checking for the presence of the "@" character would be sufficient for this particular use case.
- If the above check fails, display some kind of pop-up that explains what the whole process is intended for, something like 'Are you sure you want the word "WORD" to be added to the LanguageTool dictionary? Please double-check its spelling. Click "Yes" to continue, "No" to cancel.'

**Comment by danielnaber** [comment]
What about just removing the email field altogether? I never had time to check back with users anyway.

**Comment by janschreiber** [comment]
Very good idea in my opinion, as far as German is concerned. I have never emailed a user so far, and I can't even imagine a realistic use case. Google frequency is our best friend. We shouldn't waste our time with lengthy email correspondences about the frequency of a surname in Southern Germany or things like that.

On the other hand: For poorly documented languages, emailing back to a user and asking for sources etc. might be a good way to get in touch with other interested native speakers and eventually build a healthy community. On seconds thoughts, my opinion atm is that we should keep the email feature or make it an option per language if that is possible.

**Comment by danielnaber** [comment]
Done, should be online tonight at around 23:00 CET.

**Comment by danielnaber** [comment]
Forgot to commit a change, *now* it's actually turned off for German. Other languages, add `email=off` [here](https://github.com/languagetool-org/languagetool-website/blob/821ca6589751f8804b13a616ecea942c3e6afe15/include/header.php#L365) to also turn off asking for email address.

**Comment by janschreiber** [comment]
Thanks for clearing this up. I was wondering about this exact point when I looked at your commit 07989d1.
