### ISSUE TITLE
Highlight special characters for admins overseeing addition of new user suggestions to dictionary

### ISSUE THREAD

**Issue by janschreiber** [languagetool-org/languagetool-community-website#27]
This issue is about the page https://community.languagetool.org/suggestion/edit.

While working on the user suggestions for German, I have more than once been one step shy of adding unwanted words with special characters that are visually almost indistinguishable from their "normal" counterparts.
This screenshot shows a good example:
![2017-02-25-203635_1024x768_scrot](https://cloud.githubusercontent.com/assets/4381288/23334289/cb825c80-fb9b-11e6-8768-be0cfccfb318.png)
What looks like the two-character string 'fi' in the second token is actually the ligature 'ﬁ' (a single character).
Similar, more frequent difficulties include the distinction between the German 'ß' and the Greek lowercase beta. Depending on the font, they can be difficult to distinguish.
In my opinion it is far from trivial to do, because the set of expected standard characters is different for each language, but is it possible to highlight "unexpected" characters for the admins in some way (different background color or something)? The effort and cognitive load of checking every suggestion for those characters is too high.

**Comment by danielnaber** [comment]
I've added this (German only):

![issue27](https://cloud.githubusercontent.com/assets/857004/23334958/76029c0c-fbaa-11e6-8eb7-bd256700f465.png)

Should be online tomorrow night (but there have been issues with the auto-update, please remind me if it doesn't show up).

**Comment by janschreiber** [comment]
Thank you so much. Possible additions to the expected characters for German: éà. But if this is only a warning that does not prevent words from being added, this is exactly what I had in mind.

**Comment by janschreiber** [comment]
It is online now. Works fine.

**Comment by janschreiber** [comment]
I would really like to see the most common French accented characters in this RegEx: `éèÈÉ`. Other than that, it works like a charm.

**Comment by danielnaber** [comment]
Done, should be online later tonight.

**Comment by janschreiber** [comment]
Thank you!
