### ISSUE TITLE
Could a way to blacklist user suggestions be added?

### ISSUE THREAD

**Issue by janschreiber** [languagetool-org/languagetool-community-website#28]
There are a handful of very common spelling errors we are receiving as user suggestions over and over again. There are probably less than ten of those ('immernoch' and 'vorallem' are examples for German), but having to uncheck those again and again can become slightly annoying for the admins who look after the user suggestions.

Would it be possible to 

- add a text file with these unwanted words that serves as a blacklist,
- filter user suggestions against this blacklist before they are saved on the server side?

**Comment by danielnaber** [comment]
Related: I've just added a "Hide" link to the word management page. It can remove a word from the list without submitting the whole page. I plan to visit the page from time to time and help with removing the useless entries.

**Comment by janschreiber** [comment]
Great. Could you add a `title` attribute to the Hide link that explains what it does? It isn't self-explanatory IMO.

**Comment by danielnaber** [comment]
I've renamed it and added a title (not deployed yet).
