### ISSUE TITLE
Table content is ignored by WikiCheck

### ISSUE THREAD

**Issue by milekpl** [languagetool-org/languagetool-community-website#6]
Compare this page:

http://community.languagetool.org/wikiCheck/pageCheck?url=http%3A%2F%2Fpl.wikipedia.org%2Fwiki%2FWWE_Elimination_Chamber&enabled=IMIONA_Z_APOSTROFAMI

The rule IMIONA_Z_APOSTROFAMI should work for the page (there is an error still there, even two) but it doesn't show anything. The errors are correctly detected here:

http://community.languagetool.org/feedMatches/list?lang=pl&notFixedFilter=120&categoryFilter=B%C5%82%C4%99dy+ortograficzne&filter=IMIONA_Z_APOSTROFAMI

It seems it's because tables are not handled yet. They end up in `TextConverter.visit(AstNode n)` where nothing happens.

**Comment by janschreiber** [comment]
Maybe the WikiCheck bugs should be closed now that WikiCheck is no longer developed.
